spring.application.name=server

#CORS
app.cors.allowed-origin=

#GOOGLE GEN AI
google.genai.api.key=YOUR_API_KEY

#GOOGLE OAUTH
google.oauth.client.id=
google.oauth.client.secret=
google.oauth.redirect.uri=

#JWT
jwt.secret=YOUR_SECRET
jwt.expires.in=43200

# PostgreSQL
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
