spring.application.name=server

#CORS
app.cors.allowed-origin=${CORS_ALLOWED_ORIGIN}

#GEN AI
gen.ai.api.key=${GEN_AI_API_KEY}

#GOOGLE OAUTH
google.oauth.client.id=${GOOGLE_CLIENT_ID}
google.oauth.client.secret=${GOOGLE_CLIENT_SECRET}
google.oauth.redirect.uri=${GOOGLE_REDIRECT_URI}

#GOOGLE YT Video API KEY
google.youtube.api.key=${YT_API_KEY}

#JWT
jwt.secret=${JWT_SECRET}
jwt.expires.in=${JWT_EXPIRES_IN:43200}

# PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=600000
management.health.db.enabled=false

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
