spring.application.name=server

#GOOGLE GEN AI
google.genai.api.key=YOUR_API_KEY

#GOOGLE OAUTH
google.oauth.client.id=
google.oauth.client.secret=
google.oauth.redirect.uri=

#JWT
jwt.secret=YOUR_SECRET
jwt.expires.in=43200

#H2
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Enable H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
